version = 1

[install]
boost.pkg-path = "boost"
gnumake.pkg-path = "gnumake"
clang.pkg-path = "clang"
clang-tools.pkg-path = "clang-tools"

[build.quotes-app-cpp]
version = "0.0.1"
description = "Quotes app written in C++"
command = """
  make
  make install PREFIX=$out
"""
# Need libboost.dylib at runtime.
runtime-packages = [ "boost" ]

[build.quotes-app-cpp-pure]
version = "0.0.1"
description = "Quotes app written in C++"
command = """
  make
  make install PREFIX=$out SUFFIX="-pure"
"""
sandbox = "pure"
# Need libboost.dylib at runtime.
runtime-packages = [ "boost" ]

[services]
quotes-cpp.command = "./quotes-cpp"
