version = 1

[install]
# Rust toolchain
cargo = { pkg-path = "cargo" }
rustc = { pkg-path = "rustc" }
clippy = { pkg-path = "clippy" }
rustfmt = { pkg-path = "rustfmt" }
rust-lib-src = { pkg-path = "rustPlatform.rustLibSrc" }

# Linkers
clang = { pkg-path = "clang", systems = ["aarch64-darwin"] }
gcc = { pkg-path = "gcc", systems = ["aarch64-linux", "x86_64-linux"] }

# Platform-specific libraries
# Until https://github.com/flox/flox/issues/3055 is fixed, we need all system
# types, even though it's really just needed on Mac.
#libiconv = { pkg-path = "libiconv", systems = ["aarch64-darwin", "x86_64-darwin"] }
libiconv = { pkg-path = "libiconv" }

# rust-analyzer goes in its own group because it's updated
# on a different cadence from the compiler and doesn't need
# to match versions
rust-analyzer = { pkg-path = "rust-analyzer", pkg-group = "extra" }

[build.quotes-app-rs]
command = '''
  mkdir -p $out/bin
  cargo build --release
  cp target/release/quotes-app-rs $out/bin/quotes-app-rs
'''
description = "A simple quotes server"
version = "0.1.0"
runtime-packages = ["libiconv"]

[build.quotes-app-rs-pure]
command = '''
  mkdir -p $out/bin
  cargo build --release
  cp target/release/quotes-app-rs $out/bin/quotes-app-rs-pure
'''
description = "A simple quotes server"
version = "0.1.0"
sandbox = "pure"
runtime-packages = ["libiconv"]
