version = 1

[install]
ruby.pkg-path = "ruby"

[vars]
GEM_HOME="vendor"

[hook]
 on-activate = '''
    unset CPATH
'''

[build.quotes-app-rb]
command = """
   bundle config set --local path ./vendor
   bundle install
   mkdir -p $out/{lib,bin} 
   cp -pr * $out/lib 
   mv $out/lib/quotes $out/bin/quotes-app-rb
   # Remove things that are not needed in the final package
	 rm -f $out/lib/.gitignore 
   rm -rf $out/lib/.flox
"""
version = "0.0.1"
description = "A simple Ruby app that prints a random quote from a list of quotes."

[build.quotes-app-rb-deps]
command = """
   # Don't use or update paths in the real project config.
   export BUNDLE_IGNORE_CONFIG=true

   # Pre-fetch the deps outside of the sandbox.
   export BUNDLE_PATH=$out
   export BUNDLE_CACHE_PATH=${out}/cache
   bundle cache --no-install

   # These gems appear to be duplicated irrespective of `--no-install`
   rm -rf $out/ruby
"""

[build.quotes-app-rb-pure]
command = """
   mkdir -p $out/{lib,bin}

   # Don't use or update paths in the real project config.
   export BUNDLE_IGNORE_CONFIG=true

   # Perform an isolated install using pre-fetched deps.
   export BUNDLE_PATH=$out/lib/vendor
   export BUNDLE_CACHE_PATH=${quotes-app-rb-deps}/cache
   export BUNDLE_DEPLOYMENT=true
   bundle install --standalone --local

   cp -pr * $out/lib
   mv $out/lib/quotes $out/bin/quotes-app-rb-pure
   # Remove things that are not needed in the final package
   rm -f $out/lib/.gitignore
   rm -rf $out/lib/.flox
"""
sandbox = "pure"
version = "0.0.1"
description = "A simple Ruby app that prints a random quote from a list of quotes."
