version = 1

[install]
ruby.pkg-path = "ruby"

[vars]
GEM_HOME="vendor"

[hook]
 on-activate = '''
    unset CPATH
'''

[build.quotes-app-rb]
command = """
   mkdir -p $out/{lib,bin}

   # Don't use or update paths in the real project config.
   export BUNDLE_IGNORE_CONFIG=true

   # Perform an isolated install using any existing project cache.
   export BUNDLE_PATH=$out/lib/vendor
   export BUNDLE_CACHE_PATH=vendor/cache
   export BUNDLE_DEPLOYMENT=true
   bundle install --standalone

   cp Gemfile Gemfile.lock $out/lib
   cp app.rb quotes.json $out/lib
   cp quotes $out/bin/quotes-app-rb
"""
version = "0.0.1"
description = "A simple Ruby app that prints a random quote from a list of quotes."

[build.quotes-app-rb-deps]
command = """
   # Don't use or update paths in the real project config.
   export BUNDLE_IGNORE_CONFIG=true

   # Pre-fetch the deps outside of the sandbox.
   export BUNDLE_PATH=$out
   export BUNDLE_CACHE_PATH=${out}/cache
   bundle cache --no-install

   # These gems appear to be duplicated irrespective of `--no-install`
   rm -rf $out/ruby
"""

[build.quotes-app-rb-pure]
command = """
   mkdir -p $out/{lib,bin}

   # Don't use or update paths in the real project config.
   export BUNDLE_IGNORE_CONFIG=true

   # Perform an isolated install using pre-fetched deps.
   export BUNDLE_PATH=$out/lib/vendor
   export BUNDLE_CACHE_PATH=${quotes-app-rb-deps}/cache
   export BUNDLE_DEPLOYMENT=true
   bundle install --standalone --local

   cp Gemfile Gemfile.lock $out/lib
   cp app.rb quotes.json $out/lib
   cp quotes $out/bin/quotes-app-rb-pure
"""
sandbox = "pure"
version = "0.0.1"
description = "A simple Ruby app that prints a random quote from a list of quotes."
