name: Test Manifest Builds

on:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Install Flox"
        uses: "flox/install-flox-action@main"

      - name: "Set FLOXBIN env var"
        run: echo "FLOXBIN=$(which flox)" >> $GITHUB_ENV

      - name: "Enable build features"
        run: flox config --set-bool features.build true

      - name: "Show flox binary path"
        run: echo "Flox is at $FLOXBIN"

      - name: "Run flox version"
        run: $FLOXBIN --version

      - name: "Run make"
        run: make
